In [1]:
import numpy as np

from dilpack.games.games import RockPaperScissors, BasketballOffense, NBASportsBetting

This notebook aims to explore how linear algebra and game theory may be applied in the context of sports betting. We first set up the context by introducing simple 2-party games and their payoffs before we finally formulate a sports betting game.

## Game 1: Rock Paper Scissors

The first game is the classic game of Rock Paper Scissors. For the unaware, the rules for this game are simple:
- rock beats scissors
- scissors beats paper
- paper beats rock

Both players choose either of the three and see if their choice beats the other. The winner gets a point (+1), and the loser gets negative of that (-1). For a tie game, a score of zero (0) is given. 

1) What is this payoff matrix for this game? 

In [2]:
RockPaperScissors().payoff_matrix

array([[ 0, -1,  1],
       [ 1,  0, -1],
       [-1,  1,  0]])

2) What is the expected payoff for this game, assuming that both players are equally likely to choose any of the three?

In [3]:
RockPaperScissors().calculate_expected_payoff()

0.0

3) Suppose player A has a tendency to play rock 70% of the time, 20% for paper, and 10% for scissors. Moreover, player B has a tendency to play rock 30% of the time, 10% for paper, and 60% for scissors. Which player has the more advantageous strategy?

In [4]:
RockPaperScissors([0.7, 0.2, 0.1], [0.3, 0.1, 0.6]).calculate_expected_payoff()

0.26999999999999996

## Game 2: NBA Offense

The second game to be studied is the sport of basketball. In particular, we focus on the team playing offense. A simple formulation of this game is to think of the offense having three (3) choices in shooting the ball: 
- shooting from beyong the 3PT line (worth 3 pts, least likely to go in)
- shooting a midrange shot (worth 2 pts, more likely than 3PT shot)
- shooting from under the basket (worth 2 pts, more likely than midrange)

The sport is undoubtedly a lot more complex than how it is set up here, but for now we assume simplicity. We also make some assumptions based on rules and modern-day data:
- NBA average percentages for 3PT, midrange, and UB: 36.2%, 45.15%, and 59.15%
- A team gets to shoot 60 shots in an NBA game

1) What is this payoff matrix for this game? 

In [5]:
BasketballOffense().payoff_matrix

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

2) What is the expected payoff for this game, assuming that the offense is equally likely to shoot all three kinds of shots? The expected payoff can be interpreted as the average number of points made in a normal NBA game, given the distribution of shots.

In [6]:
BasketballOffense().calculate_expected_payoff()

55.54

3) The offensive trend in modern-day NBA today is to chuck up as much 3PT shots as possible, with the other two shots being chosen less. Is this strategy better than the one presented in #2? Assume that you have 60 shots to work with.

In [7]:
BasketballOffense([40, 10, 10]).calculate_expected_payoff()

60.35

4) What is the expected payoff for making ONLY 3PT shots in a game? Is this better than the strategies presented in #2 and #3?

In [8]:
BasketballOffense([60, 0, 0]).calculate_expected_payoff()

65.16

5) What is the optimal strategy (in terms of shot distribution between 3PT-MR-UB) based on league-wide average shot percentages?

In [9]:
BasketballOffense().optimal_strategy()

(60, 0, 0)

6) For a team that has a strong frontcourt, UB percentages may significantly increase. In the 2021-2022 season, Rudy Gobert recorded a UB% of around 72.1%. With this modification of team data, would the optimal strategy in terms of shot distribution change?

In [10]:
BasketballOffense(y=[0.362, 0.4515, 0.721]).optimal_strategy()

(0, 0, 60)

## Game 3: NBA Sports Betting

We now move on from studying the offense of a basketball game, to betting on an actual basketball game. For this part, we use the NBA as a reference for all data/information used. To keep things simple, we wish to make bets on the 4 remaining teams in the NBA playoffs given a set amount of budget (at least \\$100, multiples of \\$100). The odds for the 4 teams are available online, so we shall use these as data for our calculations. NBA odds are interpreted as follows:
- Odds are based off of bets of \\$100
- An odds value of -200 means that you must bet \\$200 to gain \\$100
- An odds value of +200 means that you stand to gain \\$200 + \\$100 (original bet) = \\$300 if the team you bet on wins

For this study, the top 4 teams as of today to be used are: the Celtics, Bucks, Nets, and Nuggets. The odds for these teams, respectively, are: 400, 550, 800, 900. 

The likelihoods of each team winning (as well as none of them winning) have already been naively calculated based on current games won. A more informed analyst would incorporate other factors in calculating these probabilities, such as injury reports and playoff experience. However, to keep things simple, we will work with a simple calculation.

1) What is this payoff matrix for this game? 

In [11]:
NBASportsBetting().payoff_matrix

array([[ 400., -100., -100., -100., -100.],
       [-100.,  550., -100., -100., -100.],
       [-100., -100.,  800., -100., -100.],
       [-100., -100., -100.,  900., -100.]])

2) Suppose you have a budget of \\$400 to bet on a team(s). What is the expected payoff for this game, with your strategy being all in for the favorites of this season?

In [12]:
NBASportsBetting(strategy=[400, 0, 0, 0]).calculate_expected_payoff()

99.99999999999997

3) With the same budget, what is the expected payoff for this game given that you equally allot your budget for all 4 teams?

In [13]:
NBASportsBetting(strategy=[100, 100, 100, 100]).calculate_expected_payoff()

326.8382352941177

4) What is the optimal strategy in terms of betting allocation?

In [14]:
NBASportsBetting(money=400).optimal_strategy()

(0, 0, 0, 400)

##### Important note: the calculated expected payoffs are NOT the amount of winnings you are guaranteed to win everytime you bet with that specific strategy. Instead, it is the average amount of winnings you are expected to win over a course of a lot of seasons, given that your strategy, the odds, and probabilities of teams winning all stay the same. Of course, these are variables that constantly evolve over time, so a deeper analysis must be sought out.